spring:
  profiles:
    active: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

cloud:
  aws:
    credentials:
      accessKey: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ${SPRING_CLOUD_AWS_REGION_STATIC}
    s3:
      bucket: ${S3_BUCKET}

jwt:
  secretkey: ${JWT_SECRET}

cors:
  urls:
    - http://localhost:3000

oauth:
  kakao:
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUrl: http://localhost:3000/api/auth/callback/kakao