name: ci

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and analyze
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export SPRING_CLOUD_AWS_CREDENTIALS_ACCESSKEY=$AWS_ACCESS_KEY
          export SPRING_CLOUD_AWS_CREDENTIALS_SECRETKEY=$AWS_SECRET_KEY
          export SPRING_CLOUD_AWS_REGION_STATIC=$AWS_REGION
          export S3_BUCKET=$S3_BUCKET
          ./gradlew build sonar --info
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
        
